### ISSUE TITLE
Hello, may I ask how the label content in the (image, label) pair returned by this loader is constructed

### ISSUE THREAD

**Issue by Edisonhimself** [filipepcampos/mimic-cxr-jpg-loader#1]
Hello, may I ask how the label content in the (image, label) pair returned by this loader is constructed

**Comment by filipepcampos** [comment]
Hi! Originally, I wanted to make this loader as versatile as possible so the label content would contain all the columns in the CheXpert labels provided by MIMIC. So, for instance, if you want to access Cardiomegaly labels, you would use `labels["Cardiomegaly"]`.

I'm working a bit more on the project since I finally have some more time and recently added an additional keyword argument to the MIMICDataset class, `target_pathology = Pathology.YOUR_DESIRED_CONDITION`. This will return (img, vector with numeric labels for `YOUR_DESIRED_CONDITION`). 

I've also updated the `README` to (hopefully) better explain this behaviour.
